# @package _global_

defaults:
  - /models: edsr
  - _self_

upscale: 2

data_norm:
  mean: [0.4989248121185863, 0.24549368276091751]
  std: [0.6533769533620326, 0.5137172765330106]

dataset:
  name: mwd
  infer_lr_root: /workspace/dataset/test/mwd/x2/lr

infer:
  checkpoint: null
  save_results: true
  save_dir: ./results
  mask: /workspace/dataset/test/mwd/x2/mask.npy
  batch_size: 1
  num_workers: 4

hydra:
  run:
    dir: ./experiments/${now:%Y%m%d_%H%M%S}_infer_${models.name}_${dataset.name}_x${upscale}
  job:
    chdir: false
