defaults:
  - models: edsr
  - _self_

dataset:
  name: wind
  upscale: 2
  channels: 1
  normalize:
    mean: [4.565732]
    std: [3.1361]
  infer_lr_root: ./data/wind/Infer/LR/wind

infer:
  checkpoint: null
  save_results: true
  save_dir: ./results
  mask: null
  batch_size: 1
  num_workers: 4

hydra:
  run:
    dir: ./experiments/${now:%Y%m%d_%H%M%S}_infer_${models.name}_${dataset.name}_x${dataset.upscale}
  job:
    chdir: false
